# Generated by Django 3.1.1 on 2020-09-24 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthdate',
            field=models.DateField(default=datetime.date(2000, 1, 1), verbose_name='birthdate'),
        ),
    ]
