# Generated by Django 3.1.1 on 2020-09-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0003_profile_birthdate1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthdate',
            field=models.DateField(null=True, verbose_name='birthdate'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='middle_name',
            field=models.CharField(max_length=30, null=True, verbose_name='middle_name'),
        ),
    ]
