# Generated by Django 3.1.1 on 2020-09-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0006_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='update_time',
            field=models.TimeField(null=True, verbose_name='update_time'),
        ),
    ]
