# Generated by Django 3.1.1 on 2020-09-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0007_auto_20200927_1134'),
    ]

    operations = [
    ]
